### PR TITLE
Support for ListGroupItem

### LINKED ISSUE #37: Add support for ListGroupItem
**Feature request:**

[`ListGroupItem` has a "href" attribute](https://react-bootstrap.github.io/components.html#listgroup) and it would be great to have this same functionality with these items (so a `ListGroupItemLink` component).

### PR DESCRIPTION
**Pull request by idolizesc**
@mtscout6  I want to resolve #37 with my changes. I have followed the contribution guidelines and included tests/documentation updates as well.

### CODE REVIEW

**Comment by mtscout6** [comment]
This looks great, Thanks!

**Comment by mtscout6** [comment]
I added you as a collaborator should you find more things you wish to push. If you'd also like to push to npm since I won't have to time to do so send me your npm username and I'll give you push access as well.

**Comment by idolizesc** [comment]
Awesome! Thanks a lot. My npm username is [idolize](https://www.npmjs.com/~idolize). I'm happy to upload the new version there.

**Comment by mtscout6** [comment]
You've been added. Thanks for helping out, try and follow [semver](http://semver.org/) the best you can. I appreciate the help.

**Comment by idolizesc** [comment]
**0.13.0 published:** [npm](https://www.npmjs.com/package/react-router-bootstrap) has been updated, as well as a new [GitHub release tagged](https://github.com/mtscout6/react-router-bootstrap/releases/tag/v0.13.0). :smile:

**Comment by mtscout6** [comment]
Fantastic!

**Pull request merged**
