### PR TITLE
webpack build for bower

### PR DESCRIPTION
**Pull request by bryanlarsen**
`npm run build` will now create lib/ReactRouterBootstrap.js and
lib/ReactRouterBootstrap.min.js.  according to your CONTRIBUTING.md you
don't want these files in the PR, so make sure you add them when you
merge this PR.

A starter bower.json is included so you can upload to bower.   I have
not registered the react-router-bootstrap name.

### CODE REVIEW

**Comment by mtscout6** [comment]
Thanks! I'll look through this first thing tomorrow.

**Comment by bryanlarsen** [comment]
it would have been fine, but I updated just to make it more clear

**Comment by mtscout6** [comment]
Would you rebase and squash those changes. There's no need to apply an unnecessary merge commit for this.

**Comment by bryanlarsen** [comment]
sorry, I didn't mean to push the merge (obviously I needed it for my testing).    should be good now.

**Comment by mtscout6** [comment]
I don't think this is working quite right. So, I see the webpack output:

```
Hash: 62ddadc486606123e096
Version: webpack 1.4.15
Time: 673ms
                  Asset    Size  Chunks             Chunk Names
ReactRouterBootstrap.js  653571       0  [emitted]  main
   [0] ./lib/index.js 238 {0} [built]
   [1] ./lib/ButtonLink.js 1163 {0} [built]
   [2] ./lib/MenuItemLink.js 1442 {0} [built]
   [3] ./lib/NavItemLink.js 1167 {0} [built]
   [9] ./lib/LinkMixin.js 1837 {0} [built]
    + 169 hidden modules
```

Note the 169 hidden modules!

Also, the un-minified script is 20,978 lines of code, which is way more than necessary for this small of a library.

Around line 323 of the un-minified script I start to see React internal specific scripts.

**Comment by mtscout6** [comment]
Ah, never mind I merged in master and all was good!

**Comment by mtscout6** [comment]
I registered it with bower, so version 0.8.3 is the first bower compatible release.

**Pull request merged**
